name: build & deploy

on: [ workflow_dispatch]

    # branches: [ dev ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: build
        run: echo "Building......"
      - uses: actions/checkout@v2 
        
      - name: Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}

        run: |
            git branch
            npm install pm2 -g && pm2 install pm2-logrotate

              '
