name: build & deploy

on: [push, workflow_dispatch]

    # branches: [ dev ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: build
        run: echo "Building......"
        
      - uses: actions/checkout@v2 
      - name: Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}

        run: |
            pwd
            ls
            # cd /home/ubuntu/uptime-kuma
            git checkout master
            git pull
            npm run setup

              '
